Support optional nullable
DoclerLabs/api-client-generator pull request #86
Opened 2023-03-21 08:22 UTC by Yarre

Optional nullable might be used in the PATCH request and if the feature is behind the feature flag so here is the pull request to support it.

2023-03-21 14:25 UTC, vsouz4 requested changes

2023-03-21 14:25 UTC, vsouz4 commented on src/Generator/SchemaGenerator.php
> +    private function generateHas(Field $field): ClassMethod
I think we sorting public/protected/private everywhere here

2023-03-21 14:25 UTC, vsouz4 commented on src/Generator/SchemaMapperGenerator.php
>                  $ifStmt       = $this->builder->expr(
I guess these are now unnecessary extra spaces

2023-03-21 15:08 UTC, Yarre commented on src/Generator/SchemaMapperGenerator.php
>                  $ifStmt       = $this->builder->expr(
`make cs` doesn't fix codestyle :(

2023-03-23 12:09 UTC, vsouz4 approved these changes

2023-03-23 12:10 UTC, merged